import React, { useState, useEffect } from 'react';
import { ListingResult, MediaAsset } from '../types';

interface ResultCardProps {
  result: ListingResult;
  assets: MediaAsset[];
  onReset: () => void;
}

type Platform = 'ebay' | 'facebook' | 'etsy' | 'vinted';

export const ResultCard: React.FC<ResultCardProps> = ({ result, assets, onReset }) => {
  const [copiedField, setCopiedField] = useState<string | null>(null);
  
  // Determine valid platforms based on suitability
  // If suitability data is missing (legacy history), default to all true
  const isEbayValid = result.platformSuitability ? result.platformSuitability.ebay : true;
  const isVintedValid = result.platformSuitability ? result.platformSuitability.vinted : true;
  const isFacebookValid = result.platformSuitability ? result.platformSuitability.facebook : true;
  const isEtsyValid = result.platformSuitability ? result.platformSuitability.etsy : true;

  // Set initial platform to the first valid one
  const getInitialPlatform = (): Platform => {
    if (isEbayValid) return 'ebay';
    if (isVintedValid) return 'vinted';
    if (isFacebookValid) return 'facebook';
    if (isEtsyValid) return 'etsy';
    return 'ebay';
  };

  const [platform, setPlatform] = useState<Platform>(getInitialPlatform);
  const [selectedAssetIndex, setSelectedAssetIndex] = useState(0);

  // Update platform if result changes (e.g. loading from history)
  useEffect(() => {
    setPlatform(getInitialPlatform());
  }, [result.id]);

  const copyToClipboard = (text: string, field: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const generateReportText = () => {
    let title = result.title;
    if (platform === 'facebook') title = result.facebookTitle;
    if (platform === 'etsy') title = result.etsyTitle || result.title;
    if (platform === 'vinted') title = result.vintedTitle || result.title;

    return `
RESLL - LISTING DATA (${platform.toUpperCase()})
--------------------------------
ID: ${result.id}

TITLE:
${title}

PRICE ESTIMATE:
£${result.estimatedPrice.low} - £${result.estimatedPrice.high}

CONDITION:
${result.condition} - ${result.conditionNotes}

DESCRIPTION:
${result.description}

Generated by Resll
    `.trim();
  };

  const handleSave = async () => {
    const report = generateReportText();
    const fileName = `LISTING_${result.brand || 'ITEM'}_${result.id.slice(0, 6)}.txt`;

    if (navigator.share && navigator.canShare && navigator.canShare({ text: report })) {
      try {
        await navigator.share({
          title: result.title,
          text: report,
        });
        return;
      } catch (err) {
        console.log('Share skipped/failed, falling back to download');
      }
    }

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getProfitColor = (potential: string) => {
    switch (potential) {
      case 'High': return 'bg-mint-500 text-slate-950 shadow-[0_0_15px_rgba(16,185,129,0.5)]';
      case 'Medium': return 'bg-amber-400 text-slate-950 shadow-[0_0_15px_rgba(251,191,36,0.5)]';
      default: return 'bg-slate-600 text-gray-50';
    }
  };

  // Determine if we found an arbitrage opportunity
  const hasArbitrage = result.arbitrage?.isScreenshot && (result.arbitrage?.detectedBuyPrice || 0) > 0;
  const netProfit = result.arbitrage?.netProfit?.high || 0;
  const isProfitable = netProfit > 0;

  const activeAsset = assets.length > 0 ? assets[selectedAssetIndex] : null;

  return (
    <div className="max-w-6xl mx-auto animate-[fadeIn_0.5s_ease-out] pb-20 md:pb-0">
      
      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
        <div>
           <div className="flex items-center gap-2 mb-1">
             <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-mint-500/10 text-mint-400 border border-mint-500/30 tracking-wider">ITEM #{result.id.slice(0, 8)}</span>
             <span className="text-gray-400 text-xs uppercase tracking-wider">{new Date(result.timestamp).toLocaleDateString()}</span>
             {result.era && (
               <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-900/50 text-amber-400 border border-amber-900/50 tracking-wider">
                 {result.era}
               </span>
             )}
           </div>
           <h2 className="text-2xl font-bold text-gray-50 truncate max-w-2xl">
             {platform === 'ebay' ? result.title : 
              platform === 'facebook' ? result.facebookTitle : 
              platform === 'etsy' ? (result.etsyTitle || result.title) :
              (result.vintedTitle || result.title)}
           </h2>
        </div>
        <div className="flex gap-3 w-full sm:w-auto">
           <button 
            onClick={handleSave}
            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-gray-200 rounded-lg text-sm font-medium transition-colors"
           >
             <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
             Share
           </button>
           <button
             onClick={onReset}
             className="flex-1 sm:flex-none px-4 py-2 bg-cyan-500 hover:bg-mint-400 text-gray-50 rounded-lg text-sm font-bold transition-colors shadow-lg shadow-cyan-500/20"
           >
             Scan Next
           </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Stats & Financials */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* MEDIA GALLERY */}
          <div className="bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden group">
            <div className="aspect-square bg-slate-950 relative flex items-center justify-center">
              {activeAsset ? (
                activeAsset.type === 'video' ? (
                  <video src={activeAsset.url} controls className="w-full h-full object-contain" />
                ) : (
                  <img src={activeAsset.url} alt="Item" className="w-full h-full object-contain" />
                )
              ) : (
                 <div className="text-gray-400 flex flex-col items-center p-8 text-center">
                    <svg className="w-12 h-12 mb-2 text-slate-700" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                    <span className="text-xs font-semibold uppercase tracking-wider">Text-Only Mode</span>
                 </div>
              )}
               
              {/* FLIP VERDICT BADGE */}
              {result && (
                   <div className={`absolute bottom-4 left-4 right-4 py-2 px-4 rounded-xl font-bold text-center uppercase tracking-wider text-sm shadow-lg backdrop-blur-md bg-opacity-90 ${getProfitColor(result.profitPotential)}`}>
                       {result.profitPotential} Potential
                   </div>
               )}
            </div>
            
            {/* Thumbnails */}
            {assets.length > 1 && (
                <div className="p-2 flex gap-2 overflow-x-auto scrollbar-hide bg-slate-900 border-t border-slate-700">
                    {assets.map((asset, idx) => (
                        <div 
                            key={idx}
                            onClick={() => setSelectedAssetIndex(idx)}
                            className={`w-16 h-16 flex-shrink-0 rounded-lg overflow-hidden border-2 cursor-pointer transition-all ${selectedAssetIndex === idx ? 'border-cyan-500 opacity-100' : 'border-transparent opacity-50 hover:opacity-80'}`}
                        >
                            {asset.type === 'video' ? (
                                <div className="w-full h-full bg-slate-800 flex items-center justify-center text-gray-50 text-xs">VIDEO</div>
                            ) : (
                                <img src={asset.url} className="w-full h-full object-cover" alt="thumb" />
                            )}
                        </div>
                    ))}
                </div>
            )}
            
            <div 
              onClick={handleSave}
              className="px-4 py-3 bg-slate-800 border-t border-slate-700 flex justify-between items-center cursor-pointer hover:bg-slate-700 transition-colors group/footer"
            >
                 <span className="text-[10px] text-gray-400 uppercase font-bold tracking-wider group-hover/footer:text-cyan-400">
                    {assets.length > 0 ? `Assets (${assets.length})` : 'No Media'}
                 </span>
                 <span className="text-xs text-cyan-400 font-bold flex items-center gap-1">
                    Download Package
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                 </span>
            </div>
          </div>

          {/* ARBITRAGE DASHBOARD */}
          {hasArbitrage && result.arbitrage ? (
             <div className="bg-slate-900 border border-slate-700 rounded-2xl p-0 overflow-hidden ring-1 ring-mint-400/30">
                <div className="p-4 bg-slate-800 border-b border-slate-700 flex justify-between items-center">
                   <h3 className="font-bold text-gray-50 flex items-center gap-2">
                     <svg className="w-5 h-5 text-mint-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                     Arbitrage Analysis
                   </h3>
                   <span className={`px-2 py-1 rounded text-xs font-bold ${isProfitable ? 'bg-mint-500/20 text-mint-400' : 'bg-red-900/50 text-red-500'}`}>
                     {isProfitable ? 'PROFITABLE' : 'RISKY'}
                   </span>
                </div>
                <div className="p-6 space-y-4">
                   <div className="flex justify-between items-center">
                      <span className="text-gray-400 text-sm">Buy Price (Found)</span>
                      <span className="text-gray-50 font-medium">£{result.arbitrage.detectedBuyPrice}</span>
                   </div>
                   <div className="flex justify-between items-center text-mint-400">
                      <span className="text-sm">Est. Resell Price</span>
                      <span className="font-bold">£{result.estimatedPrice.high}</span>
                   </div>
                   <div className="h-px bg-slate-700 my-2"></div>
                   <div className="space-y-1">
                      <div className="flex justify-between items-center text-xs text-gray-400">
                        <span>eBay Fees (~{((result.arbitrage.ebayFees - 0.3) / result.estimatedPrice.high * 100).toFixed(1)}%)</span>
                        <span>- £{result.arbitrage.ebayFees}</span>
                      </div>
                      <div className="flex justify-between items-center text-xs text-gray-400">
                        <span>Est. Shipping</span>
                        <span>- £{result.arbitrage.shippingCost}</span>
                      </div>
                   </div>
                   <div className="h-px bg-slate-700 my-2"></div>
                   <div className="flex justify-between items-end">
                      <span className="text-gray-200 font-medium">Net Profit</span>
                      <div className="text-right">
                        <div className={`text-2xl font-bold ${isProfitable ? 'text-mint-400' : 'text-red-500'}`}>
                          {isProfitable ? '+' : ''}£{result.arbitrage.netProfit.high}
                        </div>
                        <div className="text-xs text-gray-400">ROI: {Math.round((result.arbitrage.netProfit.high / (result.arbitrage.detectedBuyPrice || 1)) * 100)}%</div>
                      </div>
                   </div>
                </div>
             </div>
          ) : (
            // Standard Valuation View
            <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
               <h3 className="text-gray-400 text-xs uppercase tracking-wider mb-4">UK Market Valuation</h3>
               <div className="flex items-baseline gap-2 mb-2">
                 <span className="text-4xl font-bold text-gray-50">
                   £{result.estimatedPrice.low} - £{result.estimatedPrice.high}
                 </span>
               </div>
               <p className="text-xs text-gray-400 mb-4">Based on sold listings in similar condition.</p>
               
               <div className="pt-4 border-t border-slate-700 space-y-3">
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-gray-200">Condition</span>
                   <span className={`px-2 py-0.5 rounded text-xs font-bold 
                     ${result.condition === 'New' ? 'bg-mint-500/20 text-mint-400' : 
                       result.condition === 'For Parts' ? 'bg-red-900/50 text-red-500' : 'bg-amber-900/50 text-amber-400'}`}>
                     {result.condition}
                   </span>
                 </div>
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-gray-200">Demand</span>
                   <span className={`px-2 py-0.5 rounded text-xs font-bold 
                     ${result.demandLevel === 'High Demand' ? 'bg-mint-500/20 text-mint-400' : 
                       result.demandLevel === 'Slow Mover' ? 'bg-slate-800 text-gray-400' : 'bg-blue-900/50 text-blue-300'}`}>
                     {result.demandLevel}
                   </span>
                 </div>
               </div>
            </div>
          )}

          {result.verifiedSources && result.verifiedSources.length > 0 && (
            <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
              <h3 className="text-gray-400 text-xs uppercase tracking-wider mb-2">Sources Found</h3>
              <ul className="space-y-2">
                {result.verifiedSources.slice(0, 3).map((s, i) => (
                  <li key={i} className="text-xs">
                    <a href={s.uri} target="_blank" rel="noreferrer" className="text-cyan-500 hover:text-cyan-400 hover:underline truncate block">
                      {s.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Right Column: Listing Details */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* PLATFORM TOGGLE */}
          <div className="bg-slate-900 p-1 rounded-lg flex border border-slate-700 overflow-x-auto scrollbar-hide gap-1">
            {isEbayValid && (
              <button 
                onClick={() => setPlatform('ebay')}
                className={`flex-1 min-w-[80px] py-2 text-sm font-bold rounded-md transition-all ${platform === 'ebay' ? 'bg-cyan-500 text-gray-50 shadow-lg' : 'text-gray-400 hover:text-gray-200'}`}
              >
                eBay UK
              </button>
            )}
            {isVintedValid && (
              <button 
                onClick={() => setPlatform('vinted')}
                className={`flex-1 min-w-[80px] py-2 text-sm font-bold rounded-md transition-all ${platform === 'vinted' ? 'bg-cyan-500 text-gray-50 shadow-lg' : 'text-gray-400 hover:text-gray-200'}`}
              >
                Vinted
              </button>
            )}
            {isFacebookValid && (
              <button 
                onClick={() => setPlatform('facebook')}
                className={`flex-1 min-w-[80px] py-2 text-sm font-bold rounded-md transition-all ${platform === 'facebook' ? 'bg-cyan-500 text-gray-50 shadow-lg' : 'text-gray-400 hover:text-gray-200'}`}
              >
                Facebook
              </button>
            )}
            {isEtsyValid && (
              <button 
                onClick={() => setPlatform('etsy')}
                className={`flex-1 min-w-[80px] py-2 text-sm font-bold rounded-md transition-all ${platform === 'etsy' ? 'bg-cyan-500 text-gray-50 shadow-lg' : 'text-gray-400 hover:text-gray-200'}`}
              >
                Etsy
              </button>
            )}
          </div>

          {/* Title Section */}
          <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6 relative group">
            <div className="flex justify-between items-center mb-2">
               <div className="flex flex-col">
                 <h3 className="text-gray-400 text-xs uppercase tracking-wider">
                   {platform === 'ebay' ? `Optimized Title (${result.title.length}/80 chars)` : 
                    platform === 'facebook' ? 'Human-Friendly Title (Short)' : 
                    platform === 'vinted' ? 'Vinted Standard Title' :
                    `Etsy Aesthetic Title`}
                 </h3>
                 {platform === 'facebook' && <span className="text-[10px] text-blue-400">Optimized for humans, not bots.</span>}
                 {platform === 'etsy' && <span className="text-[10px] text-amber-400">Optimized for vintage/gift search.</span>}
                 {platform === 'vinted' && <span className="text-[10px] text-mint-400">Format: Brand + Item + Size + Condition.</span>}
               </div>
               <button 
                 onClick={() => copyToClipboard(
                   platform === 'ebay' ? result.title : 
                   platform === 'facebook' ? result.facebookTitle : 
                   platform === 'vinted' ? (result.vintedTitle || result.title) :
                   result.etsyTitle || result.title, 
                   'title'
                 )}
                 className="text-xs text-cyan-500 hover:text-cyan-400 flex items-center gap-1 bg-slate-800 px-2 py-1 rounded border border-slate-700"
               >
                 {copiedField === 'title' ? 'Copied!' : 'Copy Title'}
                 <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
               </button>
            </div>
            <div className="p-3 bg-slate-800 rounded-lg border border-slate-700 text-lg font-medium text-gray-50 font-mono selection:bg-mint-400/30">
              {platform === 'ebay' ? result.title : 
               platform === 'facebook' ? (result.facebookTitle || result.title) :
               platform === 'vinted' ? (result.vintedTitle || result.title) :
               (result.etsyTitle || result.title)}
            </div>
          </div>

          {/* Description Section */}
          <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6 relative">
            <div className="flex justify-between items-center mb-2">
               <h3 className="text-gray-400 text-xs uppercase tracking-wider">Description</h3>
               <button 
                 onClick={() => copyToClipboard(result.description, 'desc')}
                 className="text-xs text-cyan-500 hover:text-cyan-400 flex items-center gap-1 bg-slate-800 px-2 py-1 rounded border border-slate-700"
               >
                 {copiedField === 'desc' ? 'Copied!' : 'Copy Body'}
                 <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
               </button>
            </div>
            <div className="p-4 bg-slate-800 rounded-lg border border-slate-700 text-sm text-gray-200 whitespace-pre-wrap font-sans leading-relaxed h-64 overflow-y-auto custom-scrollbar">
              {result.description}
            </div>
          </div>

          {/* Item Specifics Grid - ONLY SHOW FOR EBAY */}
          {platform === 'ebay' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-[fadeIn_0.3s_ease-out]">
              <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
                 <h3 className="text-gray-400 text-xs uppercase tracking-wider mb-4">Item Specifics</h3>
                 <div className="space-y-2">
                   {result.itemSpecifics?.map((spec, i) => (
                     <div key={i} className="flex justify-between text-sm border-b border-slate-800 pb-1 last:border-0">
                       <span className="text-gray-400">{spec.key}</span>
                       <span className="text-gray-200 font-medium text-right">{spec.value}</span>
                     </div>
                   ))}
                 </div>
              </div>

              <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
                 <h3 className="text-gray-400 text-xs uppercase tracking-wider mb-4">Tags & Keywords</h3>
                 <div className="flex flex-wrap gap-2">
                   {result.keywords?.map((tag, i) => (
                     <span key={i} className="px-2 py-1 bg-slate-800 text-gray-200 text-xs rounded border border-slate-700">
                       #{tag}
                     </span>
                   ))}
                 </div>
                 {result.shortDescription && (
                   <div className="mt-4 pt-4 border-t border-slate-700">
                      <h3 className="text-gray-400 text-xs uppercase tracking-wider mb-2">Short Blurb</h3>
                      <p className="text-xs text-gray-400 italic">"{result.shortDescription}"</p>
                   </div>
                 )}
              </div>
            </div>
          )}

          {/* Facebook Advice - ONLY SHOW FOR FACEBOOK */}
          {platform === 'facebook' && (
             <div className="bg-blue-900/20 border border-blue-800/50 rounded-2xl p-6 animate-[fadeIn_0.3s_ease-out]">
                <h3 className="text-blue-400 font-bold mb-2">💡 Facebook Marketplace Strategy</h3>
                <p className="text-sm text-blue-200 mb-4">
                  We have optimized your title to be short and human. Facebook algorithms penalize "Keyword Stuffing".
                </p>
                <div className="text-xs text-gray-400">
                  <span className="font-bold text-gray-50">Recommended Tags: </span>
                  {result.keywords?.slice(0, 5).join(', ')}
                </div>
             </div>
          )}

           {/* Vinted Advice - ONLY SHOW FOR VINTED */}
           {platform === 'vinted' && (
             <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-[fadeIn_0.3s_ease-out]">
                <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                       <h3 className="text-mint-400 font-bold">📦 Vinted Parcel Size</h3>
                       <p className="text-sm text-gray-200 mt-1">
                         Crucial! Select this size when listing.
                       </p>
                    </div>
                  </div>
                  <div className="text-center p-4 bg-slate-800 rounded-lg border border-slate-700">
                     <span className="text-4xl font-bold text-gray-50">{result.vintedParcelSize || 'Medium'}</span>
                     <p className="text-xs text-gray-400 mt-2 uppercase tracking-wide">Recommended</p>
                  </div>
                </div>

                <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">
                   <h3 className="text-mint-400 font-bold mb-2">👗 Vinted Condition Map</h3>
                   <div className="flex justify-between items-center py-2 border-b border-slate-700">
                     <span className="text-sm text-gray-400">Your Item</span>
                     <span className="font-bold text-gray-50">{result.condition}</span>
                   </div>
                   <div className="flex justify-between items-center py-2">
                     <span className="text-sm text-gray-400">Select on Vinted</span>
                     <span className="font-bold text-cyan-400">
                       {result.condition === 'New' ? 'New with tags' : 
                        result.condition === 'Like New' ? 'New without tags' : 
                        result.condition === 'Good' ? 'Very good' : 
                        'Satisfactory'}
                     </span>
                   </div>
                </div>
             </div>
          )}

          {/* Etsy Advice - ONLY SHOW FOR ETSY */}
          {platform === 'etsy' && (
             <div className="grid grid-cols-1 gap-6 animate-[fadeIn_0.3s_ease-out]">
               <div className="bg-amber-900/10 border border-amber-900/30 rounded-2xl p-6">
                 <div className="flex justify-between items-start mb-4">
                   <div>
                      <h3 className="text-amber-400 font-bold">🛒 Etsy Listing Strategy</h3>
                      <p className="text-sm text-amber-200 mt-1">
                        Use all 13 tags. Focus on era ({result.era || 'Vintage'}) and gift appeal.
                      </p>
                   </div>
                   {result.era && (
                     <span className="bg-amber-900/50 text-amber-400 px-3 py-1 rounded-full text-xs font-bold border border-amber-900">
                       Era: {result.era}
                     </span>
                   )}
                 </div>
                 
                 <div className="bg-slate-800 p-4 rounded-lg border border-slate-700">
                   <div className="flex justify-between items-center mb-2">
                     <h4 className="text-xs text-gray-400 uppercase font-bold">Etsy Tags (13)</h4>
                     <button 
                       onClick={() => copyToClipboard(result.etsyTags?.join(', ') || '', 'tags')}
                       className="text-xs text-amber-400 hover:text-amber-300"
                     >
                       {copiedField === 'tags' ? 'Copied!' : 'Copy All'}
                     </button>
                   </div>
                   <div className="flex flex-wrap gap-2">
                     {result.etsyTags?.map((tag, i) => (
                       <span key={i} className="px-3 py-1 bg-amber-900/20 text-amber-200 border border-amber-900/30 rounded-full text-xs">
                         {tag}
                       </span>
                     ))}
                   </div>
                 </div>
               </div>
             </div>
          )}

        </div>
      </div>
    </div>
  );
};